#ifndef BOARDCONFIG_H
#define BOARDCONFIG_H

// Peripherial configuration goes here
#define configUSE_LED						1
#define configUSE_CONSOLE_UART				1
#define configUSE_SPI						1

// Define board LEDs here
#define LED_1_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_2_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_3_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_ALL_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_1_PORTBASE						GPIO_PORTF_BASE
#define LED_2_PORTBASE						GPIO_PORTF_BASE
#define LED_3_PORTBASE						GPIO_PORTF_BASE
#define LED_ALL_PORTBASE					GPIO_PORTF_BASE
#define LED_RED_PORTBASE					LED_1_PORTBASE
#define LED_BLUE_PORTBASE					LED_2_PORTBASE
#define LED_GREEN_PORTBASE					LED_3_PORTBASE
#define LED_1_PIN 							GPIO_PIN_1
#define LED_2_PIN 							GPIO_PIN_2
#define LED_3_PIN 							GPIO_PIN_3
#define LED_RED								LED_1_PIN
#define LED_BLUE 							LED_2_PIN
#define LED_GREEN 							LED_3_PIN

// Define console UART here
#define CONSOLEUARTPERIPHERIAL				SYSCTL_PERIPH_UART0
#define CONSOLEUARTPINPERIPHERIAL			SYSCTL_PERIPH_GPIOA
#define CONSOLEUARTPERIPHERIALBASE			UART0_BASE
#define CONSOLEUARTPINPERIPHERIALBASE		GPIO_PORTA_BASE
#define CONSOLEUARTRXPINTYPE				GPIO_PA0_U0RX
#define CONSOLEUARTTXPINTYPE				GPIO_PA1_U0TX
#define CONSOLEUARTRXPIN					GPIO_PIN_0
#define CONSOLEUARTTXPIN 					GPIO_PIN_1

// Define SPI here
#define SPIPERIPHERIAL						SYSCTL_PERIPH_SSI0
#define SPIPINPERIPHERIAL					SYSCTL_PERIPH_GPIOA
#define SPIPERIPHERIALBASE					SSI0_BASE
#define SPIPINPERIPHERIALBASE				GPIO_PORTA_BASE
#define SPISCLKPINTYPE						GPIO_PA2_SSI0CLK
#define SPISFSSPINTYPE						GPIO_PA3_SSI0FSS
#define SPISOMIPINTYPE						GPIO_PA4_SSI0RX
#define SPISIMOPINTYPE						GPIO_PA5_SSI0TX
#define SPISCLKPIN							GPIO_PIN_2
#define SPISFSSPIN							GPIO_PIN_3
#define SPISOMIPIN							GPIO_PIN_4
#define SPISIMOPIN							GPIO_PIN_5
#define SPIUDMATXCHANNEL					UDMA_CHANNEL_SSI0TX
#define SPIUDMARXCHANNEL					UDMA_CHANNEL_SSI0RX
#define SPIPERIPHERIALINT					INT_SSI0

// Define SPI chip select (CS) pin here
// CS: PA3
#define SPICSPINPERIPHERIAL					SYSCTL_PERIPH_GPIOA
#define SPICSPINPERIPHERIALBASE				GPIO_PORTA_BASE
#define SPICSPIN 							GPIO_PIN_3

// Define ADS1298 data ready pin here (input)
// DRDY: PE4
#define ADS1298_DRDYPINPERIPHERIAL			SYSCTL_PERIPH_GPIOE
#define ADS1298_DRDYPORTBASE				GPIO_PORTE_BASE
#define ADS1298_DRDYPIN 					GPIO_PIN_4
#define ADS1298_DRDYPORT_INT				INT_GPIOE

// Define ADS1298 start conversion pin here
// START: PA6
#define ADS1298_STARTPINPERIPHERIAL			SYSCTL_PERIPH_GPIOA
#define ADS1298_STARTPINPERIPHERIALBASE		GPIO_PORTA_BASE
#define ADS1298_STARTPIN 					GPIO_PIN_6

#endif // BOARDCONFIG_H
